### ISSUE TITLE
Put the data in a table

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy-bot-old#43]
It would be much easier to read the pull requests at http://reviews.sympy.org/ if they were in a table.  If we could then sort the columns of that table, and perhaps even narrow down results per column, that would be great (like the tables at google-melange.com, except I'm not a fan of that particular implementation).

**Comment by certik** [comment]
I have just implemented the tables, you can sort the columns, as well as search in the whole table. Currently there is a table for mergeable and another for non-mergeable requests, not sure currently if this is a good design or not. The alternative is to add a column "mergeable" and have just one table, but since you almost always want to sort by mergeable, as well as to quickly see whether there is any request that applies cleanly, so far I just created two tables.

**Comment by asmeurer** [comment]
Nice.  This is way better.  Now we just need to add some more columns to the table. I'll open a new issue with my ideas.
